services:
  app:
    image: front
    build:
      context: ./library-frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./library-frontend/:/usr/src/app
    container_name: front
    environment: 
      - REACT_APP_GRAPHQL_HTTP=${REACT_APP_BACKEND_URL}
      - REACT_APP_GRAPHQL_WS=${REACT_APP_BACKEND_URL}
  server:
    image: back
    build:
      context: ./library-backend
      dockerfile: Dockerfile
    volumes:
      - ./library-backend/:/usr/src/app
    container_name: back
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
     - 3456:27017
    environment:
      MONGO_INITDB_DATABASE: library_db
    volumes:
      - mongo_data:/data/db
    command: mongod --noauth
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
  
  debug-helper:
    image: busybox

volumes:
  mongo_data: