POST http://localhost:3001/api/blogs
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2NDM1ZmFiMDYyZDRhZTE0ZjlhMzkzMWEiLCJpYXQiOjE2ODE0MTYyNDQsImV4cCI6MTY4MTQxOTg0NH0.vTpz0CBIc0OsRSoA2nBz0BbrKMnN_U-I6N9TrydRWcQ

// admin
{
    "title": "second authorized blog",
    "author": "admin",
    "url": "fullstack.rar",
    "user": "6435fab062d4ae14f9a3931a"
}
