PUT http://localhost:3001/api/users/admin@gmail.com
Content-Type: "application/json"
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluQGdtYWlsLmNvbSIsInVzZXJfaWQiOjMsInNlc3Npb25faWQiOjEsImlhdCI6MTc0ODgzNjIwOX0.Pc5NsDDfYQf5WrbClBQXOKwCO2hzODpSiUxhkWHk4XI

{
  "username": "administrator@gmail.com"
}